name: store
description: Run ci-info and save the result as artifact
inputs:
  cache-name:
    description: cache name
    required: false
    default: ci-info
  github_token:
    description: GitHub Access Token
    required: false
    default: ${{ github.token }}
runs:
  using: composite
  steps:
    - run: |
        tempfile="$(mktemp)"
        ci-info run | sed "s/^export //" > "${tempfile}"
        cat "$tempfile" >> "$GITHUB_ENV"
        . "$tempfile"
        cp "$tempfile" "${CI_INFO_TEMP_DIR}/env"
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
    - uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
      with:
        name: ci-info
        path: ${{env.CI_INFO_TEMP_DIR}}
