name: restore
description: Restore ci-info result from an artifact
inputs:
  cache-name:
    description: 'cache name'
    required: false
    default: ci-info
  path:
    description: 'Destination path'
    required: false
outputs:
  download-path:
    description: 'Path to the downloaded artifact'
    value: ${{steps.download.outputs.download-path}}
runs:
  using: composite
  steps:
    - uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
      id: download
      with:
        name: ${{inputs.cache-name}}
        path: ${{inputs.path}}
    - run: cat "$CI_INFO_TEMP_DIR/env" | sed "s|^CI_INFO_TEMP_DIR=.*$|CI_INFO_TEMP_DIR=$CI_INFO_TEMP_DIR|" >> "$GITHUB_ENV"
      shell: bash
      env:
        CI_INFO_TEMP_DIR: ${{steps.download.outputs.download-path}}
